[package]
name = "digest"
version = "0.8.1"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Traits for cryptographic hash functions"
documentation = "https://docs.rs/digest"
repository = "https://github.com/RustCrypto/traits"
keywords = ["digest", "crypto", "hash"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.12"
blobby = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx", optional = true, tag = "sgx_1.0.9" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", optional = true, tag = "v1.0.9" }

[features]
std = ["mesalock_sgx"]
dev = ["blobby"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/traits" }

[package.metadata.docs.rs]
features = ["std"]
