[package]
name = "stream-cipher"
version = "0.3.2"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Stream cipher traits"
documentation = "https://docs.rs/stream-cipher"
repository = "https://github.com/RustCrypto/traits"
keywords = ["crypto", "stream-cipher", "trait"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.12"
blobby = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx", optional = true, tag = "sgx_1.0.9" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true, tag = "v1.0.9" }

[features]
std = ["mesalock_sgx"]
dev = ["blobby"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/traits" }

[package.metadata.docs.rs]
features = [ "std" ]
